import React, { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Star, ShieldCheck, FileText, ChevronLeft, ChevronRight, Quote, Loader2 } from 'lucide-react';
import { publicService } from '../../services/publicService';
import FilePreviewModal, { getFullFileUrl } from '../public/FilePreviewModal';

const getCountryFlag = (country) => {
  if (!country) return '🌍';
  const c = country.toLowerCase();
  if (c.includes('benin') || c.includes('bénin')) return '🇧🇯';
  if (c.includes('cameroon') || c.includes('cameroun')) return '🇨🇲';
  if (c.includes('senegal') || c.includes('sénégal')) return '🇸🇳';
  if (c.includes('ivoire') || c.includes('coast') || c.includes('ivory')) return '🇨🇮';
  return '🌍';
};

const defaultTestimonials = [
  {
    studentName: 'Loïc Fossi',
    program: 'Software Engineering Intern',
    story: 'The hybrid internship program at InterLink was career-defining. Working on enterprise React/Node.js CRM tools under expert supervisor guidance, with daily task reviews and inline AI report generators, accelerated my learning ten-fold.',
    rating: 5,
    verified: true,
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80&auto=format&fit=crop',
    flag: '🇨🇲',
    city: 'Douala',
    destinationCountry: 'Cameroon',
    accentColor: '#06b6d4',
  },
  {
    studentName: 'Nafissatou Diallo',
    program: 'Cybersecurity Analyst Intern',
    story: 'Conducting network penetration testing audits and configuring Linux threat defenses gave me solid practical experience. The verified portfolio generated by InterLink directly landed me my security auditor job at a leading bank.',
    rating: 5,
    verified: true,
    photo: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&q=80&auto=format&fit=crop',
    flag: '🇸🇳',
    city: 'Dakar',
    destinationCountry: 'Senegal',
    accentColor: '#ef4444',
  },
  {
    studentName: 'Arthur Zang',
    program: 'AI Development Intern',
    story: 'Training machine learning algorithms and integrating Gemini APIs into context-aware systems was incredibly rewarding. The supervisor\'s structured feedback on my daily task board kept me highly motivated.',
    rating: 5,
    verified: true,
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&q=80&auto=format&fit=crop',
    flag: '🇨🇲',
    city: 'Yaoundé',
    destinationCountry: 'Cameroon',
    accentColor: '#8b5cf6',
  },
];

function StarRating({ count }) {
  return (
    <div style={{ display: 'flex', gap: 3 }}>
      {Array.from({ length: 5 }).map((_, i) => (
        <Star
          key={i}
          className="w-4 h-4"
          fill={i < count ? '#f59e0b' : 'none'}
          color={i < count ? '#f59e0b' : 'rgba(255,255,255,0.15)'}
        />
      ))}
    </div>
  );
}

function TestimonialsSection() {
  const { t } = useTranslation();
  const [active, setActive] = useState(0);
  const [animating, setAnimating] = useState(false);
  const [direction, setDirection] = useState(1);
  const [fetchedTestimonials, setFetchedTestimonials] = useState([]);
  const [loading, setLoading] = useState(true);
  const [previewDoc, setPreviewDoc] = useState(null);
  const [touchStart, setTouchStart] = useState(null);
  const autoplayRef = useRef(null);

  useEffect(() => {
    const loadTestimonials = async () => {
      try {
        const data = await publicService.getTestimonials();
        const verifiedList = data.filter(item => item.isVerified || item.verified);
        setFetchedTestimonials(verifiedList);
      } catch (err) {
        console.error('Failed to load testimonials:', err);
      } finally {
        setLoading(false);
      }
    };
    loadTestimonials();
  }, []);

  const list = fetchedTestimonials.length > 0 ? fetchedTestimonials : defaultTestimonials;

  const goTo = (index, dir = 1) => {
    if (animating) return;
    setAnimating(true);
    setDirection(dir);
    setTimeout(() => {
      setActive((index + list.length) % list.length);
      setAnimating(false);
    }, 340);
  };

  const prev = () => goTo(active - 1, -1);
  const next = () => goTo(active + 1, 1);

  useEffect(() => {
    if (list.length <= 1) return;
    autoplayRef.current = setInterval(next, 6000);
    return () => clearInterval(autoplayRef.current);
  }, [list.length, active]);

  const handleTouchEnd = (e) => {
    if (touchStart === null) return;
    const dist = touchStart - e.changedTouches[0].clientX;
    if (Math.abs(dist) > 45) dist > 0 ? next() : prev();
    setTouchStart(null);
  };

  const item = list[active];
  if (!item) return null;

  const author = item.authorName || item.studentName || 'Anonymous Intern';
  const programName = item.programId || item.program || 'Technology Track';
  const story = item.content || item.story || '';
  const rating = item.rating || 5;
  const isVerified = item.isVerified ?? item.verified ?? false;
  const photo = item.photo;
  const validationDoc = item.internalValidationDoc;
  const resolvedPhoto = photo
    ? getFullFileUrl(photo)
    : 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&q=80&auto=format&fit=crop';
  const flag = item.flag || getCountryFlag(item.destinationCountry || item.location);
  const cityText = item.city || '';
  const countryText = item.destinationCountry || '';
  const place = item.location || (cityText && countryText ? `${cityText}, ${countryText}` : cityText || countryText || '');
  const accentColor = item.accentColor || '#3b82f6';
  const quoteText = story.startsWith('testimonials.quote_') ? t(story) : story;

  return (
    <section
      id="testimonials"
      className="page-section"
      style={{
        background: 'var(--bg-color)',
        borderTop: '1px solid var(--glass-border)',
        borderBottom: '1px solid var(--glass-border)',
        position: 'relative',
        zIndex: 10,
        overflow: 'hidden',
      }}
    >
      {/* Background glows */}
      <div style={{
        position: 'absolute', top: '15%', left: '-8%',
        width: 500, height: 500, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(6,182,212,0.06), transparent 70%)',
        pointerEvents: 'none',
      }} />
      <div style={{
        position: 'absolute', bottom: '10%', right: '-8%',
        width: 450, height: 450, borderRadius: '50%',
        background: 'radial-gradient(circle, rgba(139,92,246,0.05), transparent 70%)',
        pointerEvents: 'none',
      }} />

      <div className="wide-container" style={{ maxWidth: 1280, margin: '0 auto', position: 'relative', zIndex: 2 }}>
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '3.5rem' }}>
          <div className="section-label" style={{ display: 'inline-flex', marginBottom: '1rem' }}>
            💬 SUCCESS STORIES
          </div>
          <h2 className="section-heading">
            Hear From Our Successful<br />
            <span className="gradient-text" style={{ background: 'linear-gradient(135deg, #06B6D4 0%, #8B5CF6 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Tech Interns.</span>
          </h2>
          <p className="section-sub">Dozens of software engineers, cybersecurity analysts, and AI developers have accelerated their professional career pathways with InterLink.</p>
        </div>

        {loading ? (
          <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: 360 }}>
            <Loader2 className="w-10 h-10 text-blue-500 animate-spin" />
          </div>
        ) : (
          <div style={{ position: 'relative' }}>
            {/* Carousel viewport */}
            <div
              onTouchStart={(e) => setTouchStart(e.touches[0].clientX)}
              onTouchEnd={handleTouchEnd}
              style={{
                position: 'relative',
                overflow: 'hidden',
                borderRadius: 28,
                minHeight: 340,
              }}
            >
              <div
                className="glass"
                style={{
                  borderRadius: 28,
                  padding: '3rem 3.5rem',
                  borderTop: `3px solid ${accentColor}40`,
                  boxShadow: `0 40px 80px -20px ${accentColor}20, var(--glass-shadow)`,
                  position: 'relative',
                  overflow: 'hidden',
                  opacity: animating ? 0 : 1,
                  transform: animating ? `translateX(${direction > 0 ? '30px' : '-30px'})` : 'translateX(0)',
                  transition: 'opacity 0.34s ease, transform 0.34s ease',
                  display: 'grid',
                  gridTemplateColumns: '1fr auto',
                  gap: '3rem',
                  alignItems: 'center',
                }}
              >
                {/* Glow */}
                <div style={{
                  position: 'absolute', top: -50, right: -50,
                  width: 200, height: 200, borderRadius: '50%',
                  background: `radial-gradient(circle, ${accentColor}18, transparent 70%)`,
                  pointerEvents: 'none',
                }} />

                {/* Quote watermark */}
                <div style={{
                  position: 'absolute', top: 20, right: 24,
                  color: 'rgba(255,255,255,0.04)',
                  pointerEvents: 'none',
                }}>
                  <Quote className="w-20 h-20" style={{ transform: 'rotate(180deg)' }} />
                </div>

                {/* Left: Content */}
                <div style={{ position: 'relative', zIndex: 2 }}>
                  {/* Rating + badge */}
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1.75rem' }}>
                    <StarRating count={rating} />
                    {isVerified && (
                      <span
                        className="flex items-center gap-1 text-[0.625rem] font-extrabold uppercase tracking-widest px-2.5 py-1 rounded-full"
                        style={{
                          background: 'rgba(16, 185, 129, 0.1)',
                          color: '#34d399',
                          border: '1px solid rgba(52, 211, 153, 0.2)',
                        }}
                      >
                        <ShieldCheck className="w-3.5 h-3.5" />
                        Verified Intern
                      </span>
                    )}
                  </div>

                  {/* Quote text */}
                  <p style={{
                    fontSize: '1.15rem',
                    color: 'var(--text-secondary)',
                    lineHeight: 1.8,
                    fontStyle: 'italic',
                    letterSpacing: '-0.01em',
                    marginBottom: '2rem',
                  }}>
                    "{quoteText}"
                  </p>

                  {/* Author */}
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                    <img
                      src={resolvedPhoto}
                      alt={author}
                      onError={(e) => { e.target.src = 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&q=80&auto=format&fit=crop'; }}
                      style={{
                        width: 56, height: 56, borderRadius: '50%',
                        objectFit: 'cover',
                        border: `3px solid ${accentColor}40`,
                      }}
                    />
                    <div>
                      <div style={{ fontWeight: 800, fontSize: '1rem', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 6 }}>
                        {author} <span>{flag}</span>
                      </div>
                      <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', fontWeight: 600, marginTop: 2 }}>
                        {programName}{place && ` • ${place}`}
                      </div>
                    </div>
                  </div>

                  {/* Validation doc */}
                  {validationDoc && (
                    <button
                      onClick={() => setPreviewDoc({ url: validationDoc, name: `Academic Verification — ${author}` })}
                      className="flex items-center gap-1.5 text-[0.7rem] font-bold text-teal-400 hover:text-teal-300 transition-colors bg-teal-500/10 hover:bg-teal-500/20 border border-teal-500/20 hover:border-teal-500/40 px-3.5 py-2 rounded-xl cursor-pointer w-fit mt-4"
                    >
                      <FileText className="w-3.5 h-3.5" />
                      View Verification Document
                    </button>
                  )}
                </div>

                {/* Right: accent circle with number */}
                <div style={{
                  flexShrink: 0,
                  width: 120, height: 120,
                  borderRadius: '50%',
                  background: `${accentColor}12`,
                  border: `2px solid ${accentColor}30`,
                  display: 'flex', flexDirection: 'column',
                  alignItems: 'center', justifyContent: 'center',
                  position: 'relative', zIndex: 2,
                }}>
                  <span style={{ fontSize: '2rem', fontWeight: 900, color: accentColor, lineHeight: 1 }}>
                    {String(active + 1).padStart(2, '0')}
                  </span>
                  <span style={{ fontSize: '0.65rem', fontWeight: 700, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.1em', marginTop: 4 }}>
                    / {String(list.length).padStart(2, '0')}
                  </span>
                </div>
              </div>
            </div>

            {/* Navigation row */}
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
              marginTop: '2rem',
            }}>
              {/* Dots */}
              <div style={{ display: 'flex', gap: '0.5rem' }}>
                {list.map((t2, i) => {
                  const acc = t2.accentColor || '#3b82f6';
                  return (
                    <button
                      key={i}
                      type="button"
                      onClick={() => goTo(i, i > active ? 1 : -1)}
                      aria-label={`Show testimonial ${i + 1}`}
                      style={{
                        width: i === active ? 32 : 10,
                        height: 10,
                        borderRadius: 999,
                        background: i === active ? accentColor : 'rgba(255,255,255,0.12)',
                        border: 'none',
                        cursor: 'pointer',
                        transition: 'all 0.35s ease',
                        padding: 0,
                      }}
                    />
                  );
                })}
              </div>

              {/* Prev / Next buttons */}
              <div style={{ display: 'flex', gap: '0.75rem' }}>
                <button
                  onClick={prev}
                  aria-label="Previous testimonial"
                  style={{
                    width: 48, height: 48, borderRadius: '50%',
                    border: '1px solid var(--glass-border)',
                    background: 'var(--glass-bg)',
                    color: 'var(--text-primary)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    cursor: 'pointer',
                    transition: 'all 0.25s ease',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.08)'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
                  onMouseLeave={e => { e.currentTarget.style.background = 'var(--glass-bg)'; e.currentTarget.style.transform = 'none'; }}
                >
                  <ChevronLeft className="w-5 h-5" />
                </button>
                <button
                  onClick={next}
                  aria-label="Next testimonial"
                  style={{
                    width: 48, height: 48, borderRadius: '50%',
                    border: '1px solid var(--glass-border)',
                    background: 'var(--glass-bg)',
                    color: 'var(--text-primary)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    cursor: 'pointer',
                    transition: 'all 0.25s ease',
                  }}
                  onMouseEnter={e => { e.currentTarget.style.background = 'rgba(255,255,255,0.08)'; e.currentTarget.style.transform = 'translateY(-2px)'; }}
                  onMouseLeave={e => { e.currentTarget.style.background = 'var(--glass-bg)'; e.currentTarget.style.transform = 'none'; }}
                >
                  <ChevronRight className="w-5 h-5" />
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Trust standards footer */}
        <div style={{ marginTop: '5rem', textAlign: 'center' }}>
          <p style={{
            fontSize: '0.75rem', fontWeight: 800,
            letterSpacing: '0.15em', textTransform: 'uppercase',
            color: 'var(--text-muted)', marginBottom: '2rem',
          }}>
            TRUSTED METHODOLOGIES & INDUSTRY ALIGNMENTS
          </p>
          <div
            className="trust-logos-grid"
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(4, 1fr)',
              gap: '1.25rem',
              alignItems: 'center',
            }}
          >
            {[
              { label: 'Enterprise Standard Tech', icon: '💻' },
              { label: 'AI-Powered Mentorship', icon: '🤖' },
              { label: 'ISO-Aligned Security', icon: '🛡️' },
              { label: 'Verified Web Portfolios', icon: '🎓' },
            ].map((p, i) => (
              <div
                key={i}
                className="trust-logo-card glass"
                style={{
                  display: 'flex', alignItems: 'center', gap: '0.625rem',
                  padding: '0.85rem 1.25rem', borderRadius: 16,
                  background: 'rgba(255,255,255,0.02)',
                  border: '1px solid var(--glass-border)',
                  justifyContent: 'center',
                  transition: 'all 0.3s ease',
                  cursor: 'default',
                }}
              >
                <span style={{ fontSize: '1.35rem' }}>{p.icon}</span>
                <span style={{ fontSize: '0.8125rem', fontWeight: 700, color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>
                  {p.label}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {previewDoc && (
        <FilePreviewModal
          isOpen={!!previewDoc}
          onClose={() => setPreviewDoc(null)}
          fileUrl={previewDoc.url}
          fileName={previewDoc.name}
        />
      )}

      <style>{`
        @media (max-width: 900px) {
          #testimonials .glass[style*="grid-template-columns"] {
            grid-template-columns: 1fr !important;
          }
          #testimonials .glass > div:last-child {
            display: none !important;
          }
        }
        @media (max-width: 1000px) {
          .trust-logos-grid { grid-template-columns: repeat(2, 1fr) !important; }
          .trust-logo-card { padding: 0.625rem 1rem !important; }
        }
        @media (max-width: 500px) {
          .trust-logo-card span:last-child { font-size: 0.75rem !important; }
        }
      `}</style>
    </section>
  );
}

export default TestimonialsSection;

